---
- name: register the current terminal profile
  shell: defaults read "com.apple.Terminal" "Default Window Settings"
  register: terminal_profile_result
  changed_when: False

- name: store the terminal profile in /tmp
  copy:
    src: 'Dracula.terminal'
    dest: '/tmp/Dracula.terminal'
  when: terminal_profile_result.stdout != "Dracula"

- name: install the terminal profile
  shell: open /tmp/Dracula.terminal
  when: terminal_profile_result.stdout != "Dracula"

- name: set the Default Window Settings
  osx_defaults:
    domain: com.apple.Terminal
    key: Default Window Settings
    type: string
    value: 'Dracula'
    state: present

- name: set the Startup Window Settings
  osx_defaults:
    domain: com.apple.Terminal
    key: Startup Window Settings
    type: string
    value: 'Dracula'
    state: present
