---
- name: install personal brew apps
  homebrew: name={{item}} state=latest
  with_items:
    - zsh-autosuggestions
    - zsh-completions
    - zsh-git-prompt
    - zsh-history-substring-search
    - zsh-syntax-highlighting
    
- name: place the different configuration files into place
  copy:
    src: '{{item}}'
    dest: '~/.{{ item }}'
  with_items:
    - zshrc
