---
- name: install personal brew apps
  homebrew: name={{item}} state=latest
  with_items:
    - zsh-autosuggestions
    - zsh-completions

    
- name: place the different configuration files into place
  copy:
    src: '{{item}}'
    dest: '~/.{{ item }}'
  with_items:
    - zshrc

- name: place the different configuration files into place
  shell: rm -f ~/.zcompdump; compinit
