---
- name: tap the repos
  homebrew_tap: tap=superbrothers/zsh-kubectl-prompt state=present

- name: install personal brew apps
  homebrew: name={{item}} state=latest
  with_items:
    - zplug
    - zsh-autosuggestions
    - zsh-completions
    - zsh-git-prompt
    - zsh-history-substring-search
    - zsh-syntax-highlighting
    - zsh-kubectl-prompt
    
- name: place the different configuration files into place
  copy:
    src: '{{item}}'
    dest: '~/.{{ item }}'
  with_items:
    - zshrc
